name: "build"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest"
            args: "--target aarch64-apple-darwin"
          - platform: "macos-latest"
            args: "--target x86_64-apple-darwin"
          - platform: "ubuntu-22.04"
            args: ""
          - platform: "windows-latest"
            args: ""

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev build-essential curl wget file libxdo-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev patchelf

      - name: install frontend dependencies
        run: bun install

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: ${{ matrix.args }}
        id: tauri

      - uses: actions/upload-artifact@v4
        if: matrix.platform == 'ubuntu-22.04'
        with:
          name: binaries-linux
          path: |
            ${{ github.workspace }}/src-tauri/target/**/*.deb
            ${{ github.workspace }}/src-tauri/target/**/*.rpm
            ${{ github.workspace }}/src-tauri/target/**/*.AppImage

      - uses: actions/upload-artifact@v4
        if: matrix.platform == 'macos-latest' && contains(matrix.args, 'aarch64-apple-darwin')
        with:
          name: binaries-macos-aarch64
          path: |
            ${{ github.workspace }}/src-tauri/target/**/*.dmg
            ${{ github.workspace }}/src-tauri/target/**/*.app

      - uses: actions/upload-artifact@v4
        if: matrix.platform == 'macos-latest' && contains(matrix.args, 'x86_64-apple-darwin')
        with:
          name: binaries-macos-x86_64
          path: |
            ${{ github.workspace }}/src-tauri/target/**/*.dmg
            ${{ github.workspace }}/src-tauri/target/**/*.app

      - uses: actions/upload-artifact@v4
        if: matrix.platform == 'windows-latest'
        with:
          name: binaries-windows
          path: |
            ${{ github.workspace }}/src-tauri/target/**/*.exe
            ${{ github.workspace }}/src-tauri/target/**/*.msi
